### PR TITLE
Issue 4629 - Fix caption content reset after setting change

### LINKED ISSUE #4629: Image`s caption bug
### Description

Image`s caption bug

### Step-by-step reproduction instructions

1. Add image
2. Add caption
3. Change colour 
4. Change caption 
5. Change color again 

### Screenshots, screen recording, code snippet

https://jam.dev/c/fd936f08-4404-437b-a1c8-25a55da15ddf

### URL and/or Code editor

_No response_

### How to fix it

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Fybex**
# Description

Fixes #4629 

# How Has This Been Tested?
See video from issue, the problem is in speed. To reproduce it needs to be done very fast

# Test checklist

**_ Front/Back Testing _**

-   [x] Try to reproduce on master
-   [x] Ensure that it's fixed

**_ Pre-Code Testing _**

-   [ ] Try to reproduce on master
-   [ ] Ensure that it's fixed
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings/errors

## Summary by CodeRabbit

- **Refactor**
    - Optimized the timeout setting for image processing to enhance performance.

### CODE REVIEW

File: src/blocks/image-maxi/edit.js [hunk 1]
```diff
@@ -499,7 +499,7 @@ class edit extends MaxiBlockComponent {
 																			newState
 																		);
 																	},
-																	600
+																	10
```
Comment (Fybex) [inline src/blocks/image-maxi/edit.js:502]: Set the same state update timeout value as in text-maxi

**Review by Olekrut — CHANGES_REQUESTED** [review]
https://jam.dev/c/e29249f5-cf74-49d5-9146-d40027d913e1
can re-produce yet

**Review by Olekrut — APPROVED** [review]

**Review by elzadj — APPROVED** [review]
