### PR TITLE
Issue 4517 - Fix and enhance e2e DC tests

### LINKED ISSUE #4517: Fix and enhance DC tests
### Original issue

While creating DC, we added some tests that runs correctly on localhost, but return error on Github. In order to approve the PR, skipped the tests. So, need to be fixed.

In the other side, we should improve the tests with:
1. Test that tests the component behaviour.
2. Tests for Image, Button and Link component

### MVP solution

_No response_

### How to fix it

_No response_

### PR DESCRIPTION
**Pull request by myroslavve**
# Description

Fixes #4517 

# How Has This Been Tested?
Checked that all tests pass, and added tests described in the issue.

# Test checklist

**_ Front/Back Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type

**_ Pre-Code Testing _**

-   [ ] Test the component in normal state in sidebar
-   [ ] Test the component in hover state in sidebar (if hover exists)
-   [ ] Check that the settings work on frontend
-   [ ] Check that backend works and saves the settings after the editor reload
-   [ ] Same 1-4 points for the toolbar
-   [ ] Same 1-4 points on responsive
-   [ ] Test the block inside the grid (Container + Row + Column)
-   [ ] Test the block as a standalone block
-   [ ] Duplicate the block, test that the settings of the first do not affect the second
-   [ ] Test with 2 blocks of the same type
-   [ ] Check no commented code and no unnecessary imports
-   [ ] Standards of the project have been followed
-   [ ] No errors/warnings on console

# Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings/errors
-   [ ] I have added/updated tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Tests**
	- Activated previously skipped test cases for dynamic content across multiple components (author, category, media, page, post, site).
	- Updated test selectors and block identifiers to use a new naming convention.
	- Added image cleanup functionality in media tests.
	- Increased timeout durations for certain test operations.
	- Added a new test case for verifying dynamic content link functionality.
	- Enhanced test coverage for dynamic content components, including text and image blocks.

- **Chores**
	- Updated import statements in utility functions.
	- Added a new utility function to remove uploaded images from the media library.
	- Introduced a new debugging configuration for end-to-end tests in the development environment.
	- Enhanced error handling in the image uploading process.
	- Improved caching mechanism and error handling in dynamic content options.
	- Added additional CSS class names for styling in the Dynamic Content component.

### CODE REVIEW

File: e2e-tests/utils/addImageToLibrary.js [hunk 1]
```diff
@@ -3,17 +3,48 @@ const addImageToLibrary = async page => {
 		fetch(
 			'https://upload.wikimedia.org/wikipedia/commons/7/77/Delete_key1.jpg'
```
Comment (elzadj) [inline e2e-tests/utils/addImageToLibrary.js:4]: This image is 404, let's change it to something from our server? https://img.maxiblocks.com/2024/12/Pure-Image-Dark-PID-PRO-108-1734710451-273045251-1734710451-1041076938.webp or any other image from img.maxiblocks.com

I also can upload a specific one to use here.

**Review by elzadj — CHANGES_REQUESTED** [review]
Great one, just 2 questions (see my code comments):
1. Opening post-new
2. Image is 404

File: e2e-tests/components/dynamic-content/component.spec.js [hunk 2]
```diff
@@ -0,0 +1,309 @@
...
+});
+
+describe('Dynamic content component for image blocks', () => {
+	beforeAll(async () => {
+		await createNewPost();
+		await addImageToLibrary(page);
+	});
+
+	afterAll(async () => {
+		await page.goto('http://localhost:8889/wp-admin/post-new.php');
```
[the remark this answers is not in the document]
Comment (myroslavve) [reply e2e-tests/components/dynamic-content/component.spec.js]: `removeUploadedImage` uploaded image is using `wp.data` which is only available in gutenberg editor pages. 
I could make the test manually go on the media page and delete the image, but we're not testing that, so I decided to just remove it with js.

Added a comment to that function to note that it only works on editor pages.

File: e2e-tests/utils/addImageToLibrary.js (hunk 1 above)
Comment (myroslavve) [reply e2e-tests/utils/addImageToLibrary.js]: Cool, I replaced it with the one you shared here.

**Review by elzadj — APPROVED** [review]
